#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
  cloud: #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云 OSS
#不同的服务器，地址不同
tencent:
  appId:
  secretId:
  secretKey:
  region:
  photoBucket:


